name: testing
on:
  push:
    branches: [ "master" ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Git repository code
        uses: actions/checkout@v3
      - name: Install dependecies
        run: npm install
      - name: Test
        run: npm test
      - name: Test local action
        uses: ./allure-report-action
        with:
          allure_results: build/allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history



